# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d5fca1ac30800ed1d29c5374b0b031c64343b643de96bfc2761a2536505ff38fdd509cdf098bf04113137451e4fea42f37e9a5219112c767f8e1950071f11f0

test:
  secret_key_base: 7625aca753305f41a37b6f03495230025b5d137da177bbfe7202d1e1bc13cf33ce2b81e16a6292909d7e8f570d721b9004b0f9e8ea2d820498b76a41c386ebc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
